### ISSUE TITLE
Deleting a networkacllist applied on privategateway fails without error

### ISSUE THREAD

**Issue by ddegoede** [MissionCriticalCloud/cosmic#143]
If a networkacllist is applied to a private gateway and I try to delete the that networkacllist the job eventually timeout, but does not give an error stating that the networkacllist is still in use

**Comment by remibergsma** [comment]
@ddegoede I think this PR fixes your issue, at least the part about not getting the error returned: https://github.com/MissionCriticalCloud/cosmic/pull/145
