### ISSUE TITLE
No access to Slack channel for external emails (not @schubergphilis.com)

### ISSUE THREAD

**Issue by jsaintrocc** [MissionCriticalCloud/cosmic#440]
The Slack channel requires a @schubergphilis.com email address to join.  Is there a community forum or somewhere else I could use for installation questions?

**Comment by borisroman** [comment]
@jsaintrocc You can join us any time! Please send your mail address to bschrijver@schubergphilis.com.

We'll get in touch!

**Comment by jsaintrocc** [comment]
Thanks Borris.  I just sent you the email.
