### ISSUE TITLE
PXE boot option per network tier on the RVM

### ISSUE THREAD

**Issue by rudiheinen** [MissionCriticalCloud/cosmic#758]
Hi,

I'd like the possibility to configure PXE on a per tier bases in de DHCP options (66,67)
Currently got it running by adding the below config manually en restarting dnsmasq.

Example config:
[root@r-****** ~]# cat /etc/dnsmasq.d/pxe.conf
dhcp-option=tag:interface-eth5,67,<pxe image>
dhcp-option=tag:interface-eth5,66,<pxe host>

And adding the MAC to dhcphosts:
[root@r-****** ~]# cat /etc/dhcphosts.txt
...
...
00:00:00:00:00:00,set:11_11_11_11,11.11.11.11,hostname,infinite

Would be nice :)

Thanks!

**Comment by remibergsma** [comment]
Fixed in #780
