### ISSUE TITLE
Unable to use LoadBalancer VIP from within VPC tier

### ISSUE THREAD

**Issue by ddegoede** [MissionCriticalCloud/cosmic#856]
At the moment it is not possible to reach a public IP with a Load Balancer rule from within the VPC where it is attached however this seems to work if the public IP is configured with a Port Forward rule to a single virtual machine.

As a system engineer I would like to be able to use the same functionality for Load Balancer rules to avoid single points of failures.

Issue raised in name of @rezgaa

**Comment by 954alberto** [comment]
Hello guys, 
I tested that by adding the following iptable rule on the router vms will allow the traffic from inside the network to the loadbalancer IP.

iptables --append INPUT --match tcp --protocol tcp --src private-network/24 --dst public-ip/32 --jump ACCEPT

Kind regards

**Comment by 954alberto** [comment]
Hello guys, 
Do you have updates on this?

**Comment by sanderv32** [comment]
Fixed in PR #874
