### ISSUE TITLE
When using a network offering with remote gateway, it's not possible to deploy a VM as gateway

### ISSUE THREAD

**Issue by rarenerd** [MissionCriticalCloud/cosmic#863]
I'd like to have the option to use a VM (with for example Cisco vASA) as a gateway instead of the RouterVM.

Currently the only way to do this is by using a remote gateway, however this prevents the gateway IP from being handed out to a VM (as it's considered an excluded IP).

In a typical deployment I'd like to reserve IP addresses ending with .1 and .2 for my ASA cluster, setting .1 as gateway. The RVMs can then use .3 and .4.

One way I can see this work is to set an IP exclusion list for .1 and .2, gateway to .1 and have an option to explicitly bypass the exclusion list and gateway IP restriction for my firewall instances and NICs.

**Comment by remibergsma** [comment]
Design notes:

1) Add new flag "Remote Gateway VM" in template properties.

2) Usage of this field:
When:
A) VPC offering == "Remote gateway" AND vm_template == "Remote Gateway VM" ==> assign gateway ip to this VM (specified in request).
B) VPC offering == "Remote gateway" AND vm_template == "Remote Gateway VM" ==> allow reserved ip to be assigned this VM (specified in request).

Option:
Add boolean on network properties to allow/disallow a Remote gateway VM to acquire the gateway ip
